# Config
import = [
  # "~/.config/alacritty/colors/nord.toml",
  # "~/.config/alacritty/colors/baitong.toml",
  "~/.config/alacritty/colors/solarized_dark.toml",
]

live_config_reload = true

[shell]
program = "/opt/homebrew/bin/fish"

# [env]
# TERM = "xterm-256color"

[window]
dynamic_title = false
dynamic_padding = false
option_as_alt = 'OnlyLeft'
decorations = "ButtonLess" # "None"
padding = { x = 5, y = 5 }

# opacity = 0.7
# blur = true

[scrolling]
history = 100000
multiplier = 3

[cursor]
style = { blinking = "Off"}

[debug]
render_timer = false

[font]
normal = { family = "FiraCode Nerd Font Mono" }

# find installed fonts (macOS): fc-list : family | sort -f
# "Liga SFMono Nerd Font"
# "FiraCode Nerd Font Mono"
# "GohuFont uni14 Nerd Font Mono"

size = 14.0
offset = { x = 0, y = 3 }

[mouse]
hide_when_typing = true

