require("config.options")
require("config.keymaps")
require("config.autocommands")
require("config.commands")
require("config.lazy")
-- require("config.terminal")
require("config.quickfix")
require("config.find")

vim.cmd.colorscheme("kanagawa-wave")
-- vim.cmd.colorscheme("base16-black-metal-gorgoroth")
-- vim.cmd.colorscheme("e-ink")
