[nvim.files]
"nvim/" = { target = "~/.config/nvim/", type = "symbolic" }

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[psql.files]
"psql/psqlrc" = "~/.psqlrc"

[shell.files]
"fish" = "~/.config/fish"
"github/gitconfig" = "~/.gitconfig"
"tmux/tmux.conf" = "~/.tmux.conf"
"shell/bat" = "~/.config/bat/config"
"shell/bottom.toml" = "~/.config/bottom/bottom.toml"
"shell/fd.ignore" = "~/.config/fd/ignore"
"shell/htoprc" = "~/.config/htop/htoprc"

[scripts.files]
scripts = "~/.config/scripts"

