[settings]
default_target_type = "automatic"

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[bin.files]
bin = "~/.local/bin"

[fish.files]
"fish" = "~/.config/fish"

[ghostty.files]
"ghostty" = "~/.config/ghostty"

[git.files]
"git/config" = "~/.config/git/config"
"git/ignore" = "~/.config/git/ignore"
"git/commit_template" = "~/.config/git/commit_template"

[homebrew]
depends = []

[nvim.files]
"nvim" = { target = "~/.config/nvim/", type = "symbolic" }

[psql.files]
"psql/psqlrc" = "~/.psqlrc"

[scripts.files]
scripts = "~/.config/scripts"

[shell.files]
"shell/bat" = "~/.config/bat/config"
"shell/bottom.toml" = "~/.config/bottom/bottom.toml"
"shell/fd.ignore" = "~/.config/fd/ignore"
"shell/htoprc" = "~/.config/htop/htoprc"
"shell/curl" = "~/.curlrc"
"shell/wget" = "~/.wgetrc"

[format.files]
"format/sqlfluff" = "~/.sqlfluff"
"format/clang" = "~/.clang-format"

[taskwarrior.files]
task = "~/.config/task"

[tmux.files]
"tmux/tmux.conf" = "~/.tmux.conf"
