[nvim.files]
"nvim/" = { target = "~/.config/nvim/", type = "symbolic" }

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[ghostty.files]
"ghostty" = "~/.config/ghostty"

[psql.files]
"psql/psqlrc" = "~/.psqlrc"

[shell.files]
"fish" = "~/.config/fish"
"github/gitconfig" = "~/.gitconfig"
"tmux/tmux.conf" = "~/.tmux.conf"
"shell/bat" = "~/.config/bat/config"
"shell/bottom.toml" = "~/.config/bottom/bottom.toml"
"shell/fd.ignore" = "~/.config/fd/ignore"
"shell/htoprc" = "~/.config/htop/htoprc"

[org.files]
task = "~/.config/task"

[scripts.files]
scripts = "~/.config/scripts"

[bin.files]
bin = "~/.local/bin"

[sqlfluff.files]
"sqlfluff/config" = "~/.sqlfluff"
