[helpers]

[default]
depends = []

[default.files]

[default.variables]

[shell.variables]
# Local variables: install, uninstall, update, autoremove, user_color
install = "echo not defined"
uninstall = "echo not defined"
update = "echo not defined"
autoremove = "echo not defined"

[nvim.files]
"nvim/custom" = { target = "~/.config/nvim/lua/custom", type = "symbolic" }

[git.files]
"gitconfig" = "~/.gitconfig"

[tmux.files]
"tmux.conf" = "~/.tmux.conf"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/aliases.fish" = "~/.config/fish/aliases.fish"
"fish/functions" = "~/.config/fish/functions"

[alacritty.files]
"alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"
"alacritty/colors" = "~/.config/alacritty/colors"

[alacritty.variables]
font_family = "Menlo"
font_size = 14

[scripts.files]
scripts = "~/.config/scripts"

[bottom.files]
"bottom.toml" = "~/.config/bottom/bottom.toml"

[fd.files]
"fd.ignore" = "~/.config/fd/ignore"

[bat.files]
"bat" = "~/.config/bat/config"

[htop.files]
"htoprc" = "~/.config/htop/htoprc"
